#!/bin/bash

[ -z "$DOTFILES" ] && source ./utils.sh

# set zsh as default shell
if [[ $SHELL = *zsh ]]; then
  echo "zsh is already the default shell."
else
  echo "Setting zsh as default shell..."
  sudo sh -c "echo $(which zsh) >> /etc/shells"
  chsh -s $(which zsh)
fi

symlink $DOTFILES/zsh/antigen.zsh $HOME/.antigen.zsh
symlink $DOTFILES/zsh/p10k.zsh $HOME/.p10k.zsh
symlink $DOTFILES/zsh/.zshrc $HOME/.zshrc

# zsh tools
symlink $DOTFILES/.wezterm.lua $HOME/.wezterm.lua
symlink $DOTFILES/.fdignore $HOME/.fdignore
