#!/bin/zsh -e

source ./utils.sh

if [[ -d ~/.config/nvim ]]; then
  git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
else
  echo "nvim already exists at ~/.config/nvim"
fi

symlink $DOTFILES/nvim $HOME/.config/nvim
symlink $DOTFILES/nvim $HOME/.nvim
symlink $DOTFILES/nvim/init.vim $HOME/.nvimrc
symlink $DOTFILES/nvim-config $HOME/.config/nvim/lua/user
symlink $DOTFILES/vimrc $HOME/.vimrc

