#!/bin/bash

[ -z "$DOTFILES" ] && source ./utils.sh

# Source asdf (cross-platform)
source "$(brew --prefix asdf)/libexec/asdf.sh"

plugins=$(asdf plugin list)
asdf_install_plugin() {
  if [[ $plugins = "*$1*" ]]; then
    echo "plugin $1 already installed"
  else
    asdf plugin add $1
  fi
}

asdf_install_plugin java
asdf_install_plugin nodejs
asdf_install_plugin python
asdf_install_plugin ruby
asdf_install_plugin direnv

# Install and set global versions (asdf 0.18+ uses 'set -u' instead of 'global')
asdf install java $DEFAULT_JAVA_VERSION
asdf set -u java $DEFAULT_JAVA_VERSION
asdf install nodejs $DEFAULT_NODE_VERSION
asdf set -u nodejs $DEFAULT_NODE_VERSION
asdf install python $DEFAULT_PYTHON_VERSION
asdf set -u python $DEFAULT_PYTHON_VERSION
asdf install ruby $DEFAULT_RUBY_VERSION
asdf set -u ruby $DEFAULT_RUBY_VERSION

# Setup asdf-direnv integration
# This creates ~/.config/asdf-direnv/zshrc which is sourced in .zshrc
# Note: asdf 0.18+ doesn't route plugin commands through `asdf`, so we call the script directly
bash ~/.asdf/plugins/direnv/lib/commands/command-setup.bash --shell zsh --version latest
