#!/bin/zsh -e

source ./utils.sh

git submodule update --init

# macOS config
defaults write com.apple.finder AppleShowAllFiles YES.

# link dotfiles
[ -d $DOTFILES ] || symlink $HOME/projects/joshm1/dotfiles $DOTFILES

mkdir -p $HOME/.config

symlink $DOTFILES/git/gitconfig $HOME/.gitconfig
symlink $DOTFILES/git/gitignore $HOME/.gitignore

symlink $DOTFILES/ruby/gemrc $HOME/.gemrc

source ./setup-homebrew
source ./setup-zsh
source ./setup-vim
# run this lazily when we call asdf for the first time
# source ./setup-asdf

# these deprecated in favor of asdf
# source ./setup-ruby
# source ./setup-python
# source ./setup-nodejs

# fzf: install useful keybindings and fuzzy completion
[[ ! -f ~/.fzf.zsh ]] && /opt/homebrew/opt/fzf/install

# private config files should be in Dropbox
source ./setup-dropbox

# zsh-history has dropbox dependency
source ./setup-zsh-history

source ./setup-postgres

# clone oh-my-zsh - do not run installer because our .zshrc already has includes the oh-my-zsh config
# [[ ! -d ~/.oh-my-zsh ]] && \
#   git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
