#!/bin/zsh -e

source ./utils.sh

if ! type brew >/dev/null 2>&1; then
  echo "Installing homebrew..."
  # install homebrew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /Users/josh/.zprofile
  echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/josh/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "Homebrew is already installed."
fi

symlink $DOTFILES/homebrew/Brewfile $HOME/Brewfile
bundle_installed_file=$DOTFILES/homebrew/.installed
if [[ ! -f $bundle_installed_file ]]; then
  brew tap homebrew/bundle
  for brewfile in $(ls $DOTFILES/homebrew); do
    brewfile_path=$DOTFILES/homebrew/$brewfile
    echo "Running brew bundle for $brewfile_path..."
    brew bundle --file=$brewfile_path
  done
  echo $(date) >> $bundle_installed_file
else
  echo "Homebrew bundle has already been run. Delete $bundle_installed_file to run again"
fi

