#!/bin/zsh -e

[ -z "$DOTFILES" ] && source ./utils.sh

dropbox_device_zsh_history_file() {
  echo -n $DROPBOX_DIR/dotfiles/.zsh_history.$LOCAL_DEVICE_ID
}

if [[ ! -f $LOCAL_DEVICE_ID_FILE || -z $LOCAL_DEVICE_ID ]]; then
  vared -p 'What would you like to name this device? ' -c LOCAL_DEVICE_ID

  echo $LOCAL_DEVICE_ID > $LOCAL_DEVICE_ID_FILE
  if [ -f $(dropbox_device_zsh_history_file) ]; then
    echo "The device zsh_history file exists: $(dropbox_device_zsh_history_file)"
    vared -p "Do you want to copy ~/.zsh_history to $(dropbox_device_zsh_history_file) (y/n)? " -c overwrite_device_zsh_history_file
  else
    overwrite_device_zsh_history_file=yes
  fi

  if [[ "$overwrite_device_zsh_history_file" == y* ]]; then
    cp $HOME/.zsh_history $(dropbox_device_zsh_history_file)
  else
    echo "Skipping cp ~/.zsh_history $(dropbox_device_zsh_history_file)"
  fi
fi

symlink $(dropbox_device_zsh_history_file) $HOME/.zsh_history
