#!/bin/bash

# install nvm/nodejs

source ./utils.sh

export NVM_DIR="$HOME/.nvm"

if [ ! -d ~/.zsh-nvm ]; then
  echo "Cloning zsh-nvm (Oh My Zsh plugin)..."
  git clone https://github.com/lukechilds/zsh-nvm ~/.zsh-nvm
else
  echo "zsh-nvm already installed."
fi

if [ ! -d ~/.nvm ]; then
  echo "Installing nvm..."
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_VERSION/install.sh | bash
else
  echo "nvm is already installed."
fi

[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

if ! nvm ls --no-alias | grep $DEFAULT_NODE_VERSION >/dev/null 2>&1; then
  echo "Installing node version $DEFAULT_NODE_VERSION with nvm..."

  nvm install $DEFAULT_NODE_VERSION
  nvm alias default $DEFAULT_NODE_VERSION
else
  echo "node version $DEFAULT_NODE_VERSION is already installed."
fi

if ! nvm alias default | grep $DEFAULT_NODE_VERSION >/dev/null 2>&1; then
  nvm alias default $DEFAULT_NODE_VERSION
fi

nvm install-latest-npm
